### ISSUE TITLE
Whitespace at beginning of line

### ISSUE THREAD

**Issue by JJK96** [occivink/kakoune-snippets#13]
I have the following snippets

```
    set -add buffer snippets \
    "comment" "/*" %{snippets-insert %{/*
 * $1
 */}}
```
I would like to have the whilespace before the `*` characters to persist into the snippets, currently it seems to be removed

**Comment by occivink** [comment]
I don't think snippet files will solve the indentation problem, we inherently need something dynamic so that you don't have to match your snippet definition with your preferred `indentwidth`. 
One thing that we *could* say is that instead of using `${indent}`, leading tabs are automatically converted to match `indentwidth`. Thoughts on this?

Btw the undesirable consequence I was mentioning is for example your ability to do 
```
set -add snippets 'For-loop' 'for' %{for (int $1 = 0; $1 < $2; ++$1)
                                     ${indent}$3
                                     }}
```
as that will be interested like that in the buffer:
```
for (int $1 = 0; $1 < $2; ++$1)
                                     ${indent}$3
                                     }
```
However, that particular problem should be solved by snippet files so I'm inclined to go with the change I mentioned earlier.

**Comment by andreyorst** [comment]
What if language determines that it should be indented with spaces? Should snippet definition contain tabs or spaces?

**Comment by andreyorst** [comment]
> One problem for me would be that I would need to insert a literal tab

At the beginning of the line? I think that this is really rare case for snippets.

**Comment by JJK96** [comment]
I don't think it is, If you have a snippet that inserts a block, then you usually want indentation. 
If we do this implementation:

> leading tabs are automatically converted to match indentwidth

Then you would need a tab character at the beginning of the line.
