### ISSUE TITLE
Dependency section

### ISSUE THREAD

**Issue by JJK96** [occivink/kakoune-snippets#2]
Maybe it is a good idea to include a dependency section. 
For a starter it seems to depend on `perl`.

**Comment by occivink** [comment]
Right, I figured I would document all this stuff before I merge it in master

**Comment by JJK96** [comment]
That's a sane decision, sorry for being so quick

**Comment by andreyorst** [comment]
By the way, why Perl?

**Comment by occivink** [comment]
No particular reason, being an interpreted language makes it easy to distribute and it's geared towards text processing. I also knew a bit of perl from writing my gdb script (which I ported from awk for similar reasons). It could have been python, but I don't know it very well and I generally have a poor opinion of it (but maybe that's misguided). Lua could be a contender too and I know it better, but the language is not that strong for text processing (limited "patterns" instead of regex).

It's not a particularly good language to write in imo (the typing, error handling and terse syntax) but it does the job for text processing.
